// Copyright 2024 Chainguard, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pkg/service/apko/apko.proto

package apko

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApkoService_BuildLayers_FullMethodName = "/apko.v1.ApkoService/BuildLayers"
	ApkoService_Health_FullMethodName      = "/apko.v1.ApkoService/Health"
)

// ApkoServiceClient is the client API for ApkoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApkoService provides apko layer generation as a gRPC service.
// This enables fault isolation, retries, and independent scaling of apko workers.
type ApkoServiceClient interface {
	// BuildLayers builds apko layers from an image configuration and returns
	// a reference to the image in a registry.
	BuildLayers(ctx context.Context, in *BuildLayersRequest, opts ...grpc.CallOption) (*BuildLayersResponse, error)
	// Health returns the health status of the service.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type apkoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApkoServiceClient(cc grpc.ClientConnInterface) ApkoServiceClient {
	return &apkoServiceClient{cc}
}

func (c *apkoServiceClient) BuildLayers(ctx context.Context, in *BuildLayersRequest, opts ...grpc.CallOption) (*BuildLayersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildLayersResponse)
	err := c.cc.Invoke(ctx, ApkoService_BuildLayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apkoServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ApkoService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApkoServiceServer is the server API for ApkoService service.
// All implementations must embed UnimplementedApkoServiceServer
// for forward compatibility.
//
// ApkoService provides apko layer generation as a gRPC service.
// This enables fault isolation, retries, and independent scaling of apko workers.
type ApkoServiceServer interface {
	// BuildLayers builds apko layers from an image configuration and returns
	// a reference to the image in a registry.
	BuildLayers(context.Context, *BuildLayersRequest) (*BuildLayersResponse, error)
	// Health returns the health status of the service.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedApkoServiceServer()
}

// UnimplementedApkoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApkoServiceServer struct{}

func (UnimplementedApkoServiceServer) BuildLayers(context.Context, *BuildLayersRequest) (*BuildLayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildLayers not implemented")
}
func (UnimplementedApkoServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedApkoServiceServer) mustEmbedUnimplementedApkoServiceServer() {}
func (UnimplementedApkoServiceServer) testEmbeddedByValue()                     {}

// UnsafeApkoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApkoServiceServer will
// result in compilation errors.
type UnsafeApkoServiceServer interface {
	mustEmbedUnimplementedApkoServiceServer()
}

func RegisterApkoServiceServer(s grpc.ServiceRegistrar, srv ApkoServiceServer) {
	// If the following call pancis, it indicates UnimplementedApkoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApkoService_ServiceDesc, srv)
}

func _ApkoService_BuildLayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildLayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoServiceServer).BuildLayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoService_BuildLayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoServiceServer).BuildLayers(ctx, req.(*BuildLayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApkoService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApkoService_ServiceDesc is the grpc.ServiceDesc for ApkoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApkoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apko.v1.ApkoService",
	HandlerType: (*ApkoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildLayers",
			Handler:    _ApkoService_BuildLayers_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ApkoService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/service/apko/apko.proto",
}
