// Copyright 2024 Chainguard, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/service/apko/apko.proto

package apko

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the health status.
type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_service_apko_apko_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_service_apko_apko_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_proto_rawDescGZIP(), []int{3, 0}
}

// BuildLayersRequest contains the parameters for building apko layers.
type BuildLayersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// image_config_yaml is the serialized apko ImageConfiguration as YAML.
	ImageConfigYaml string `protobuf:"bytes,1,opt,name=image_config_yaml,json=imageConfigYaml,proto3" json:"image_config_yaml,omitempty"`
	// arch is the target architecture (e.g., "x86_64", "aarch64").
	Arch string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	// extra_repos are additional APK repositories to use.
	ExtraRepos []string `protobuf:"bytes,3,rep,name=extra_repos,json=extraRepos,proto3" json:"extra_repos,omitempty"`
	// extra_keys are additional APK signing keys to trust.
	ExtraKeys []string `protobuf:"bytes,4,rep,name=extra_keys,json=extraKeys,proto3" json:"extra_keys,omitempty"`
	// extra_packages are additional packages to install.
	ExtraPackages []string `protobuf:"bytes,5,rep,name=extra_packages,json=extraPackages,proto3" json:"extra_packages,omitempty"`
	// max_layers is the maximum number of layers to create (default: 50).
	MaxLayers int32 `protobuf:"varint,6,opt,name=max_layers,json=maxLayers,proto3" json:"max_layers,omitempty"`
	// request_id is an optional identifier for tracing.
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// ignore_signatures disables signature verification for APK packages.
	IgnoreSignatures bool `protobuf:"varint,8,opt,name=ignore_signatures,json=ignoreSignatures,proto3" json:"ignore_signatures,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildLayersRequest) Reset() {
	*x = BuildLayersRequest{}
	mi := &file_pkg_service_apko_apko_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLayersRequest) ProtoMessage() {}

func (x *BuildLayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLayersRequest.ProtoReflect.Descriptor instead.
func (*BuildLayersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_proto_rawDescGZIP(), []int{0}
}

func (x *BuildLayersRequest) GetImageConfigYaml() string {
	if x != nil {
		return x.ImageConfigYaml
	}
	return ""
}

func (x *BuildLayersRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *BuildLayersRequest) GetExtraRepos() []string {
	if x != nil {
		return x.ExtraRepos
	}
	return nil
}

func (x *BuildLayersRequest) GetExtraKeys() []string {
	if x != nil {
		return x.ExtraKeys
	}
	return nil
}

func (x *BuildLayersRequest) GetExtraPackages() []string {
	if x != nil {
		return x.ExtraPackages
	}
	return nil
}

func (x *BuildLayersRequest) GetMaxLayers() int32 {
	if x != nil {
		return x.MaxLayers
	}
	return 0
}

func (x *BuildLayersRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BuildLayersRequest) GetIgnoreSignatures() bool {
	if x != nil {
		return x.IgnoreSignatures
	}
	return false
}

// BuildLayersResponse contains the result of building apko layers.
type BuildLayersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// image_ref is the registry reference for the built image.
	// Example: "registry:5000/apko-cache:a3f9c5d2e1b4f7a6"
	ImageRef string `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	// layer_count is the number of layers in the image.
	LayerCount int32 `protobuf:"varint,2,opt,name=layer_count,json=layerCount,proto3" json:"layer_count,omitempty"`
	// cache_hit indicates whether the image was served from cache.
	CacheHit bool `protobuf:"varint,3,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	// locked_config_yaml is the resolved configuration with pinned package versions.
	LockedConfigYaml string `protobuf:"bytes,4,opt,name=locked_config_yaml,json=lockedConfigYaml,proto3" json:"locked_config_yaml,omitempty"`
	// duration_ms is the time taken to build the layers in milliseconds.
	DurationMs    int64 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLayersResponse) Reset() {
	*x = BuildLayersResponse{}
	mi := &file_pkg_service_apko_apko_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLayersResponse) ProtoMessage() {}

func (x *BuildLayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLayersResponse.ProtoReflect.Descriptor instead.
func (*BuildLayersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_proto_rawDescGZIP(), []int{1}
}

func (x *BuildLayersResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *BuildLayersResponse) GetLayerCount() int32 {
	if x != nil {
		return x.LayerCount
	}
	return 0
}

func (x *BuildLayersResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *BuildLayersResponse) GetLockedConfigYaml() string {
	if x != nil {
		return x.LockedConfigYaml
	}
	return ""
}

func (x *BuildLayersResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// HealthRequest is an empty request for health checks.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_service_apko_apko_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_proto_rawDescGZIP(), []int{2}
}

// HealthResponse contains the health status of the service.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the current health status.
	Status HealthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=apko.v1.HealthResponse_Status" json:"status,omitempty"`
	// active_requests is the number of currently active build requests.
	ActiveRequests int32 `protobuf:"varint,2,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	// max_concurrent is the maximum number of concurrent requests allowed.
	MaxConcurrent int32 `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_service_apko_apko_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetActiveRequests() int32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *HealthResponse) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

var File_pkg_service_apko_apko_proto protoreflect.FileDescriptor

const file_pkg_service_apko_apko_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/service/apko/apko.proto\x12\aapko.v1\"\xa6\x02\n" +
	"\x12BuildLayersRequest\x12*\n" +
	"\x11image_config_yaml\x18\x01 \x01(\tR\x0fimageConfigYaml\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1f\n" +
	"\vextra_repos\x18\x03 \x03(\tR\n" +
	"extraRepos\x12\x1d\n" +
	"\n" +
	"extra_keys\x18\x04 \x03(\tR\textraKeys\x12%\n" +
	"\x0eextra_packages\x18\x05 \x03(\tR\rextraPackages\x12\x1d\n" +
	"\n" +
	"max_layers\x18\x06 \x01(\x05R\tmaxLayers\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12+\n" +
	"\x11ignore_signatures\x18\b \x01(\bR\x10ignoreSignatures\"\xbf\x01\n" +
	"\x13BuildLayersResponse\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12\x1f\n" +
	"\vlayer_count\x18\x02 \x01(\x05R\n" +
	"layerCount\x12\x1b\n" +
	"\tcache_hit\x18\x03 \x01(\bR\bcacheHit\x12,\n" +
	"\x12locked_config_yaml\x18\x04 \x01(\tR\x10lockedConfigYaml\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\x0f\n" +
	"\rHealthRequest\"\xcd\x01\n" +
	"\x0eHealthResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.apko.v1.HealthResponse.StatusR\x06status\x12'\n" +
	"\x0factive_requests\x18\x02 \x01(\x05R\x0eactiveRequests\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x92\x01\n" +
	"\vApkoService\x12H\n" +
	"\vBuildLayers\x12\x1b.apko.v1.BuildLayersRequest\x1a\x1c.apko.v1.BuildLayersResponse\x129\n" +
	"\x06Health\x12\x16.apko.v1.HealthRequest\x1a\x17.apko.v1.HealthResponseB.Z,github.com/dlorenc/melange2/pkg/service/apkob\x06proto3"

var (
	file_pkg_service_apko_apko_proto_rawDescOnce sync.Once
	file_pkg_service_apko_apko_proto_rawDescData []byte
)

func file_pkg_service_apko_apko_proto_rawDescGZIP() []byte {
	file_pkg_service_apko_apko_proto_rawDescOnce.Do(func() {
		file_pkg_service_apko_apko_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_service_apko_apko_proto_rawDesc), len(file_pkg_service_apko_apko_proto_rawDesc)))
	})
	return file_pkg_service_apko_apko_proto_rawDescData
}

var file_pkg_service_apko_apko_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_service_apko_apko_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_service_apko_apko_proto_goTypes = []any{
	(HealthResponse_Status)(0),  // 0: apko.v1.HealthResponse.Status
	(*BuildLayersRequest)(nil),  // 1: apko.v1.BuildLayersRequest
	(*BuildLayersResponse)(nil), // 2: apko.v1.BuildLayersResponse
	(*HealthRequest)(nil),       // 3: apko.v1.HealthRequest
	(*HealthResponse)(nil),      // 4: apko.v1.HealthResponse
}
var file_pkg_service_apko_apko_proto_depIdxs = []int32{
	0, // 0: apko.v1.HealthResponse.status:type_name -> apko.v1.HealthResponse.Status
	1, // 1: apko.v1.ApkoService.BuildLayers:input_type -> apko.v1.BuildLayersRequest
	3, // 2: apko.v1.ApkoService.Health:input_type -> apko.v1.HealthRequest
	2, // 3: apko.v1.ApkoService.BuildLayers:output_type -> apko.v1.BuildLayersResponse
	4, // 4: apko.v1.ApkoService.Health:output_type -> apko.v1.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_service_apko_apko_proto_init() }
func file_pkg_service_apko_apko_proto_init() {
	if File_pkg_service_apko_apko_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_service_apko_apko_proto_rawDesc), len(file_pkg_service_apko_apko_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_service_apko_apko_proto_goTypes,
		DependencyIndexes: file_pkg_service_apko_apko_proto_depIdxs,
		EnumInfos:         file_pkg_service_apko_apko_proto_enumTypes,
		MessageInfos:      file_pkg_service_apko_apko_proto_msgTypes,
	}.Build()
	File_pkg_service_apko_apko_proto = out.File
	file_pkg_service_apko_apko_proto_goTypes = nil
	file_pkg_service_apko_apko_proto_depIdxs = nil
}
