apiVersion: v1
kind: Pod
metadata:
  name: buildkit-sandbox
spec:
  runtimeClassName: gvisor
  containers:
  - name: buildkit
    image: moby/buildkit:latest
    args:
    - --oci-worker-snapshotter=native
    securityContext:
      runAsUser: 0
      capabilities:
        add:
        - SYS_ADMIN
        - NET_ADMIN
        - SETUID
        - SETGID
    volumeMounts:
    - name: buildkit-data
      mountPath: /var/lib/buildkit
  volumes:
  - name: buildkit-data
    emptyDir: {}
